apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-editor-proxy
  name: web-editor-proxy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-editor-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-editor-proxy
      name: web-editor-proxy
    spec:
      containers:
        - image: 253548970387.dkr.ecr.us-east-1.amazonaws.com/web-editor-proxy:latest
          imagePullPolicy: Always
          name: web-editor-proxy
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 1048Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
