export const potentialCookieButtonText = [
  'Accept Cookies',
  'Agree to Cookies',
  'Consent to Cookies',
  'Allow Cookies',
  'Yes to Cookies',
  'Accept All Cookies',
  'Agree and Continue',
  'Proceed with Cookies',
  'Accept and Continue',
  'Enable Cookies',
  'Confirm Cookies',
  'I Agree',
  'Accept',
  'Go Ahead with Cookies',
  'Continue with Cookies',
  'Approve Cookies',
  'Acknowledge Cookies',
  'Okay with Cookies',
  'Say Yes to Cookies',
  'Grant Cookie Permission',
];
